package commonline.cl4.response.layout;

import commonline.core.layout.AbstractCommonLineRecordLayout;


public class ResponseRecordLayout extends AbstractCommonLineRecordLayout {

    public ResponseRecordLayout() {
        fixedText("Record Status Code", 1);
        fixedNumber("Date Record Status Last Updated (CCYYMMDD)", 8);
        text("Borrower Last Name", 35);
        text("Borrower First Name", 12);
        fixedText("Borrower Middle Initial", 1);
        fixedNumber("Borrower SSN", 9);
        text("Permanent Borrower Address (line 1)", 30);
        text("Permanent Borrower Address (line 2)", 30);
        text("Permanent Borrower City", 24);
        filler(6);
        fixedText("Permanent Borrower State", 2);
        fixedNumber("Permanent Borrower Zip Code", 5);
        fixedNumber("Permanent Borrower Zip Code Suffix", 4);
        fixedText("Borrower Telephone Number", 10);
        fixedNumber("Borrower Date of Birth (CCYYMMDD)", 8);
        fixedText("Loan Type Code", 2);
        number("Requested Loan Amount", 6);
        fixedText("Deferment Request Code", 1);
        fixedText("Borrower Interest Indicator", 1);
        fixedText("EFT Authorization Code", 1);
        fixedText("Borrower Signature Code", 1);
        fixedNumber("Borrower Signature Date (CCYYMMDD)", 8);
        fixedText("CommonLine Unique Identifier", 17);
        fixedNumber("CommonLine Loan Sequence Number", 2);
        filler(1);
        fixedText("PLUS/Alternative Borrower U.S. Citizenship Status Code", 1);
        fixedText("PLUS Borrower State of Legal Residence", 2);
        fixedNumber("PLUS Borrower State Resident Since Date (CCYYMM)", 6);
        fixedText("PLUS/Alternative Borrower Default/Refund Code", 1);
        fixedText("PLUS Borrower Outstanding Loans Code", 1);
        fixedText("Alternative Student/Borrower Indicator Code", 1);
        filler(19);
        text("PLUS/Alternative Student Last Name", 35);
        text("PLUS/Alternative Student First Name", 12);
        fixedText("PLUS/Alternative Student Middle Initial", 1);
        fixedNumber("PLUS/Alternative Student SSN", 9);
        fixedNumber("PLUS/Alternative Student Date of Birth (CCYYMMDD)", 8);
        fixedText("PLUS/Alternative Student U.S. Citizenship Status Code", 1);
        fixedText("PLUS/Alternative Student Default/Refund Code", 1);
        fixedText("PLUS/Alternative Student Signature Code", 1);
        filler(20);
        fixedNumber("School ID", 8);
        filler(2);
        fixedNumber("Loan Period Begin Date (CCYYMMDD)", 8);
        fixedNumber("Loan Period End Date (CCYYMMDD)", 8);
        fixedText("Grade Level Code", 1);
        filler(1);
        fixedText("Enrollment Status Code", 1);
        fixedNumber("Anticipated Completion Date (CCYYMMDD)", 8);
        number("Cost of Attendance", 5);
        number("Expected Family Contribution Amount", 5);
        number("Estimated Financial Aid Amount", 5);
        number("Subsidized Federal Stafford Certified Amount", 5);
        number("Unsubsidized Federal Stafford Certified Amount", 5);
        number("Federal PLUS Certified Amount", 5);
        fixedNumber("School Certification Date (CCYYMMDD)", 8);
        filler(8);
        filler(8);
        number("Alternative Loan Certified Amount", 5);
        fixedNumber("Alternative Loan Application Version Code", 4);
        fixedText("School Designated Branch/Division Code", 2);
        fixedText("DUNS School ID", 9);
        fixedText("Lender ID", 6);
        number("Subsidized Federal Stafford Approved Amount", 5);
        number("Unsubsidized Federal Stafford Approved Amount", 5);
        number("Federal PLUS Approved Amount", 5);
        fixedNumber("Lender Approved/Denied Date (CCYYMMDD)", 8);
        fixedText("Lender Approved/Denied Code", 1);
        number("Alternative Loan Approved Amount", 5);
        fixedText("DUNS Lender ID", 9);
        filler(5);
        fixedText("Guarantor ID", 3);
        fixedText("Federal Application Form Code", 1);
        fixedText("DUNS Guarantor ID", 9);
        filler(11);
        fixedText("Guarantee Adjustment Indicator Code", 1);
        filler(4);
        fixedNumber("Disbursement Date 1 (CCYYMMDD)", 8);
        number("Disbursement Amount 1", 7);
        number("Origination Fee 1", 7);
        number("Guarantee Fee 1", 7);
        number("Net Disbursement Amount 1", 7);
        fixedNumber("Disbursement Date 2 (CCYYMMDD)", 8);
        number("Disbursement Amount 2", 7);
        number("Origination Fee 2", 7);
        number("Guarantee Fee 2", 7);
        number("Net Disbursement Amount 2", 7);
        fixedNumber("Disbursement Date 3 (CCYYMMDD)", 8);
        number("Disbursement Amount 3", 7);
        number("Origination Fee 3", 7);
        number("Guarantee Fee 3", 7);
        number("Net Disbursement Amount 3", 7);
        fixedNumber("Disbursement Date 4 (CCYYMMDD)", 8);
        number("Disbursement Amount 4", 7);
        number("Origination Fee 4", 7);
        number("Guarantee Fee 4", 7);
        number("Net Disbursement Amount 4", 7);
        fixedNumber("Guarantee Date (CCYYMMDD)", 8);
        number("Guarantee Amount", 5);
        fixedText("Serial Loan Code", 1);
        fixedText("MPN Confirmation Code", 1);
        fixedText("Borrower Confirmation Indicator", 1);
        filler(19);
        fixedText("Borrower Driver's License State", 2);
        text("Borrower Driver's License Number", 20);
        fixedText("Borrower References Code", 1);
        text("School Use Only", 23);
        fixedText("Disbursement 1 Hold/Release Indicator Code", 1);
        fixedText("Disbursement 2 Hold/Release Indicator Code", 1);
        fixedText("Disbursement 3 Hold/Release Indicator Code", 1);
        fixedText("Disbursement 4 Hold/Release Indicator Code", 1);
        fixedText("Promissory Note Delivery Code", 1);
        text("Foreign Postal Code", 14);
        filler(1);
        text("Lender Non-ED Branch ID", 4);
        text("Lender Use Only", 20);
        fixedText("Lender of Last Resort Code", 1);
        filler(20);
        fixedText("Disbursement Status Code 1", 1);
        fixedText("Disbursement Status Code 2", 1);
        fixedText("Disbursement Status Code 3", 1);
        fixedText("Disbursement Status Code 4", 1);
        fixedText("Response to Originator Code", 1);
        fixedText("Application Send Error Message Code 1", 3);
        fixedText("Application Send Error Message Code 2", 3);
        fixedText("Application Send Error Message Code 3", 3);
        fixedText("Application Send Error Message Code 4", 3);
        fixedText("Application Send Error Message Code 5", 3);
        fixedText("Guarantee Amount Reduction Code", 2);
        number("Total Outstanding Federal Stafford/SLS Loan Amount", 8);
        number("Total Outstanding Federal PLUS Loan Amount", 8);
        fixedText("Application/Loan Phase Code", 4);
        fixedNumber("Date Application/Loan Phase Code Last Updated (CCYYMMDD)", 8);
        text("Guarantor Use Only", 23);
        fixedNumber("Date Permanent Address Last Updated (CCYYMMDD)", 8);
        fixedText("Alternative Loan Program Type Code", 3);
        number("Alternative Borrower Total Student Loan Debt", 7);
        filler(12);
        number("Fee Paid 1", 7);
        number("Fee Paid 2", 7);
        number("Fee Paid 3", 7);
        number("Fee Paid 4", 7);
        number("Actual Interest Rate", 5);
        fixedText("Processing Type Code", 2);
        fixedText("Service Type Code", 2);
        fixedText("Revised Notice of Guarantee Indicator Cod", 1);
        number("School Refund Amount", 7);
        fixedNumber("Date of Refund to Lender (CCYYMMDD)", 8);
        text("Unique Layout Vendor Code", 4);
        fixedText("Unique Layout Identifier Code", 2);
        filler(52);
    }

    public String getCode() {
        return "@1";
    }
}
